kind: Pod # Object type
apiVersion: v1 # API Version
metadata: # Object Description
  name: testpod # Name of the object also the name of the pod
  annotations: # description of the object/pod usage
    description: Third pod with annotation.
spec: # Specifying the configuration of the containers
  containers: # Containers details 
  - name: c01 # Name of the container 
    image: ubuntu # Base image which is used to create container  
    command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5; done"]

