kind: Service
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
  - port: 80           # Exposed port from container running inside our pod of deployment object
    targetPort: 80     # This is Pod's port (clusterIP will be mapped this port which belongs to pod)
  selector: 
   name: deployment    # Apply this service to any pods which has this specific label
  type: ClusterIP      # Specifing that this service is of type ClusterIP/VIP
