kind: Pod                        # Object type Deployment
apiVersion: v1                   # API Version of Deployment Object
metadata:                        # Object Describtion
  name: yamlenvsecretpod         # Name of the object also the name of the pod
  annotations:                   # Description of the pod, it's usage.
    description: Learning Secret Objects & Secret Environment Variable. Accessing secrect object which was created using YAML script inside container using environment variable. Inject Secrets as environment variables into containers in a Pod.
  labels:                        # Defining labels details
   day: fri                      # Key1: value1
   lecture: K8S                  # Key2: value2
spec:
  containers:
   - name: c1
     image: centos
     command: ["/bin/bash", "-c", "while true; do echo Hello-Suraj; sleep 10; done;"]  # Running sleep comand for 10 secs
     env:
     - name: MYUSER1                # Defining Key of environment variable in which content of username is stored
       valueFrom:
         secretKeyRef:
           name: mysecret1           # Name of the secret object which we created earlier
           key: username1
     - name: MYUSER2                # Defining Key of environment variable in which content of username2 is stored
       valueFrom:
         secretKeyRef:
           name: mysecret1           # Name of the secret object which we created earlier
           key: username2
     - name: MYUSER3                 # Defining Key of environment variable in which content of username3 is stored
       valueFrom:
         secretKeyRef:
           name: mysecret1           # Name of the secret object which we created earlier
           key: username3
     - name: MYPASSWORD             # Defining Key of environment variable in which content of password is stored
       valueFrom:
         secretKeyRef:
           name: mysecret1           # Name of the secret object which we created earlier
           key: password


# Secrets are objects used to store and manage sensitive information, such as passwords, tokens, API keys, SSH keys, or any piece of data that you do not want to expose in plain text within your configuration files or environment variables. Storing such sensitive information in a Secret allows Kubernetes to securely pass this data to your Pods without exposing it directly in the Pod or deployment configurations.                                                 
