apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
data:
  username1: YWRtaW4=  # base64 encoded value of 'admin'
  username2: c3VyYWoK  # base64 encoded value of 'suraj'
  username3: Goku      #
  password: c2VjcmV0MTIz  # base64 encoded value of 'secret123'

