kind: Pod                        # Object type Deployment
apiVersion: v1                   # API Version of Deployment Object
metadata:                        # Object Describtion
  name: myvolsecretpod             # Name of the object also the name of the pod
  annotations:                   # Description of the pod, it's usage.
    description: Learning Secret Objects & Secret Volume Mount. creating txt files, then creating secret object of those txt files w.t.h.o. command, then accessing secret object inside container w.t.h.o. volumes & volume mounts.
  labels:                        # Defining labels details
   day: fri                      # Key1: value1
   lecture: K8S                  # Key2: value2
spec:
  containers:
   - name: c1
     image: centos
     command: ["/bin/bash", "-c", "while true; do echo Hello-Suraj; sleep 10; done;"]  # Running sleep comand for 10 secs
     volumeMounts:                                # Mount defination inside the container
      - name: testsecret                           # Specifing to which volume this containers volume should belong/linked/mapped
        mountPath: "/tmp/mysecrets"                # mysecret object folder will be mounted by to this "tmp/mysecrets" inside container
  volumes:                                       # Defining the volume
   - name: testsecret                             # Name of the volume mount 
     secret:
       secretName: mysecret                       # This should match with the secret name created in the first step

# Secrets are objects used to store and manage sensitive information, such as passwords, tokens, API keys, SSH keys, or any piece of data that you do not want to expose in plain text within your configuration files or environment variables. Storing such sensitive information in a Secret allows Kubernetes to securely pass this data to your Pods without exposing it directly in the Pod or deployment configurations.

