kind: Deployment                 # Object type Deployment
apiVersion: apps/v1              # API Version for Deployment Object
metadata:                        # Object Description
  name: mydeployment             # Name of the object also the name of the pod
  annotations:                   # Description of the pod, it's usage.
    description: Learning ResourceQuota. Learning how to deploy a pod creation based on Deployment Object, under testing nameSpace which has restricted ResourceQuota object attached/apply.
  labels:                        # Defining labels details
   day: fri                      # Key1: value1
   lecture: K8S                  # Key2: value2
spec:
  replicas: 3                    # Desired number of pods
  selector:                      # Instructing controller which container's template, pod should belong
    matchExpressions:            # This must match the container's template labels
      - {key: myname, operator: In, values: [suraj, raj , sai]}
    # - {key: myname, operator: NotIn, values: [suraj, raj , sai]}
  template:                      # Template element defines a template to launch a new pod
    metadata:
      name: testpod
      labels:                    # Defining label for container's template
        myname: suraj            # Selector's value should match the labels value given in the pod template 
    spec:                        # Specifing the congfiguration of the containers
     containers:                 # Containers details 
     - name: c01                 # Name of the container 
       image: ubuntu             # Base image which is used to create container  
       command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5; done"]
       env:                      # Defining the environment variables to be used  inside the container
       - name: MYNAME            # Key of the environment variable
         value: Suraj            # Value of the environment variable  
       - name: Class             # Key of the environment variable
         value: DevOps           # Value of the environment variable
       resources:
         requests:               # Minimum requests for resources
           cpu: "200m"