apiVersion: v1
kind: LimitRange
metadata:
  name: memory-min-max-demo-limit-range
  #description: Creating LimitRange object to give limited usage of cpu to each container. Each container inside a pod can consume maximum user define recourse (eg. 1 millicore.)
spec:
  limits: # Defining limits
  - max: # Defining default maximum cpu limit request
      memory: "1Gi" # Default maximum limit 1000 milli bytes
    min: # Defining default minimum limit request
      memory: "500Mi" # Default minimum limit 500 millibytes
    type: Container # Specifying that LimitRange should apply only for container
