apiVersion: batch/v1
kind: Job
metadata:
  name: myjob3
spec:
  parallelism: 5 # Running job in 5 pods at a time
  template:
    metadata:
      name: testjob
    spec:
      containers:
      - name: c01
        image: centos # Base image which is used to create container  
        command: ["/bin/bash", "-c", "echo Hello-World; sleep 15"]
      restartPolicy: Never
